# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_api._generated.models.active_learning_campaign_config import ActiveLearningCampaignConfig

class TestActiveLearningCampaignConfig(unittest.TestCase):
    """ActiveLearningCampaignConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActiveLearningCampaignConfig:
        """Test ActiveLearningCampaignConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActiveLearningCampaignConfig`
        """
        model = ActiveLearningCampaignConfig()
        if include_optional:
            return ActiveLearningCampaignConfig(
                name = '',
                model_type = 'GAUSSIAN_PROCESS',
                embedder_name = '',
                optimization_mode = 'INTERVAL',
                target_lb = 1.337,
                target_ub = 1.337,
                target_value = 1.337,
                discrete_targets = [
                    ''
                    ]
            )
        else:
            return ActiveLearningCampaignConfig(
                name = '',
                model_type = 'GAUSSIAN_PROCESS',
                embedder_name = '',
                optimization_mode = 'INTERVAL',
        )
        """

    def testActiveLearningCampaignConfig(self):
        """Test ActiveLearningCampaignConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
