# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_api._generated.models.active_learning_optimization_mode import ActiveLearningOptimizationMode

class TestActiveLearningOptimizationMode(unittest.TestCase):
    """ActiveLearningOptimizationMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActiveLearningOptimizationMode(self):
        """Test ActiveLearningOptimizationMode"""
        # inst = ActiveLearningOptimizationMode()

if __name__ == '__main__':
    unittest.main()
