# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_server_api._generated.models.error_type import ErrorType

class TestErrorType(unittest.TestCase):
    """ErrorType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorType(self):
        """Test ErrorType"""
        # inst = ErrorType()

if __name__ == '__main__':
    unittest.main()
