# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_server_api._generated.models.output_data import OutputData

class TestOutputData(unittest.TestCase):
    """OutputData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutputData:
        """Test OutputData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutputData`
        """
        model = OutputData()
        if include_optional:
            return OutputData(
                config = {
                    'key' : null
                    },
                derived_values = {
                    'key' : null
                    },
                split_specific_values = {
                    'key' : null
                    },
                training_iteration = [
                    null
                    ],
                test_results = {
                    'key' : null
                    },
                predictions = {
                    'key' : null
                    }
            )
        else:
            return OutputData(
        )
        """

    def testOutputData(self):
        """Test OutputData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
