# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_server_api._generated.api.proteins_api import ProteinsApi


class TestProteinsApi(unittest.TestCase):
    """ProteinsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProteinsApi()

    def tearDown(self) -> None:
        pass

    def test_taxonomy_api_v1_protein_service_taxonomy_post(self) -> None:
        """Test case for taxonomy_api_v1_protein_service_taxonomy_post

        Retrieve taxonomy data
        """
        pass


if __name__ == '__main__':
    unittest.main()
