# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_api._generated.models.output_class import OutputClass

class TestOutputClass(unittest.TestCase):
    """OutputClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutputClass:
        """Test OutputClass
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutputClass`
        """
        model = OutputClass()
        if include_optional:
            return OutputClass(
                shortcut = '',
                label = '',
                description = ''
            )
        else:
            return OutputClass(
                shortcut = '',
                label = '',
                description = '',
        )
        """

    def testOutputClass(self):
        """Test OutputClass"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
