# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_api._generated.models.common_embedder import CommonEmbedder

class TestCommonEmbedder(unittest.TestCase):
    """CommonEmbedder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommonEmbedder(self):
        """Test CommonEmbedder"""
        # inst = CommonEmbedder()

if __name__ == '__main__':
    unittest.main()
