# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_server_api._generated.api.biocentral_api import BiocentralApi


class TestBiocentralApi(unittest.TestCase):
    """BiocentralApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BiocentralApi()

    def tearDown(self) -> None:
        pass

    def test_hashes_api_v1_biocentral_service_hashes_hash_id_file_type_get(self) -> None:
        """Test case for hashes_api_v1_biocentral_service_hashes_hash_id_file_type_get

        Hashes
        """
        pass

    def test_services_api_v1_biocentral_service_services_get(self) -> None:
        """Test case for services_api_v1_biocentral_service_services_get

        Services
        """
        pass

    def test_stats_api_v1_biocentral_service_stats_get(self) -> None:
        """Test case for stats_api_v1_biocentral_service_stats_get

        Stats
        """
        pass

    def test_task_status_api_v1_biocentral_service_task_status_task_id_get(self) -> None:
        """Test case for task_status_api_v1_biocentral_service_task_status_task_id_get

        Task Status
        """
        pass

    def test_task_status_resumed_api_v1_biocentral_service_task_status_resumed_task_id_get(self) -> None:
        """Test case for task_status_resumed_api_v1_biocentral_service_task_status_resumed_task_id_get

        Task Status Resumed
        """
        pass

    def test_transfer_file_api_v1_biocentral_service_transfer_file_post(self) -> None:
        """Test case for transfer_file_api_v1_biocentral_service_transfer_file_post

        Transfer File
        """
        pass


if __name__ == '__main__':
    unittest.main()
