# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_server_api._generated.models.add_embeddings_request import AddEmbeddingsRequest

class TestAddEmbeddingsRequest(unittest.TestCase):
    """AddEmbeddingsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddEmbeddingsRequest:
        """Test AddEmbeddingsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddEmbeddingsRequest`
        """
        model = AddEmbeddingsRequest()
        if include_optional:
            return AddEmbeddingsRequest(
                h5_bytes = '',
                sequences = '',
                embedder_name = '',
                reduced = True
            )
        else:
            return AddEmbeddingsRequest(
                h5_bytes = '',
                sequences = '',
                embedder_name = '',
                reduced = True,
        )
        """

    def testAddEmbeddingsRequest(self):
        """Test AddEmbeddingsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
