# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_api._generated.models.active_learning_simulation_request import ActiveLearningSimulationRequest

class TestActiveLearningSimulationRequest(unittest.TestCase):
    """ActiveLearningSimulationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActiveLearningSimulationRequest:
        """Test ActiveLearningSimulationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActiveLearningSimulationRequest`
        """
        model = ActiveLearningSimulationRequest()
        if include_optional:
            return ActiveLearningSimulationRequest(
                campaign_config = biocentral_api._generated.models.active_learning_campaign_config.ActiveLearningCampaignConfig(
                    name = '', 
                    model_type = 'GAUSSIAN_PROCESS', 
                    embedder_name = '', 
                    optimization_mode = 'INTERVAL', 
                    target_lb = 1.337, 
                    target_ub = 1.337, 
                    target_value = 1.337, 
                    discrete_targets = [
                        ''
                        ], ),
                simulation_config = biocentral_api._generated.models.active_learning_simulation_config.ActiveLearningSimulationConfig(
                    simulation_data = [
                        biocentral_api._generated.models.sequence_training_data.SequenceTrainingData(
                            seq_id = '0', 
                            sequence = '0', 
                            label = '', 
                            set = '', 
                            mask = '', )
                        ], 
                    n_start = 1.0, 
                    start_ids = [
                        ''
                        ], 
                    n_suggestions_per_iteration = 1.0, 
                    convergence_criterion = 0.0, 
                    n_max_iterations = 1.0, )
            )
        else:
            return ActiveLearningSimulationRequest(
                campaign_config = biocentral_api._generated.models.active_learning_campaign_config.ActiveLearningCampaignConfig(
                    name = '', 
                    model_type = 'GAUSSIAN_PROCESS', 
                    embedder_name = '', 
                    optimization_mode = 'INTERVAL', 
                    target_lb = 1.337, 
                    target_ub = 1.337, 
                    target_value = 1.337, 
                    discrete_targets = [
                        ''
                        ], ),
                simulation_config = biocentral_api._generated.models.active_learning_simulation_config.ActiveLearningSimulationConfig(
                    simulation_data = [
                        biocentral_api._generated.models.sequence_training_data.SequenceTrainingData(
                            seq_id = '0', 
                            sequence = '0', 
                            label = '', 
                            set = '', 
                            mask = '', )
                        ], 
                    n_start = 1.0, 
                    start_ids = [
                        ''
                        ], 
                    n_suggestions_per_iteration = 1.0, 
                    convergence_criterion = 0.0, 
                    n_max_iterations = 1.0, ),
        )
        """

    def testActiveLearningSimulationRequest(self):
        """Test ActiveLearningSimulationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
