# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_server_api._generated.models.embed_request import EmbedRequest

class TestEmbedRequest(unittest.TestCase):
    """EmbedRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmbedRequest:
        """Test EmbedRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmbedRequest`
        """
        model = EmbedRequest()
        if include_optional:
            return EmbedRequest(
                embedder_name = '',
                reduce = True,
                database_hash = '',
                use_half_precision = True
            )
        else:
            return EmbedRequest(
                embedder_name = '',
                database_hash = '',
        )
        """

    def testEmbedRequest(self):
        """Test EmbedRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
