# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_server_api._generated.models.config_verification_response import ConfigVerificationResponse

class TestConfigVerificationResponse(unittest.TestCase):
    """ConfigVerificationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigVerificationResponse:
        """Test ConfigVerificationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigVerificationResponse`
        """
        model = ConfigVerificationResponse()
        if include_optional:
            return ConfigVerificationResponse(
                error = ''
            )
        else:
            return ConfigVerificationResponse(
        )
        """

    def testConfigVerificationResponse(self):
        """Test ConfigVerificationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
