# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_api._generated.models.active_learning_iteration_request import ActiveLearningIterationRequest

class TestActiveLearningIterationRequest(unittest.TestCase):
    """ActiveLearningIterationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActiveLearningIterationRequest:
        """Test ActiveLearningIterationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActiveLearningIterationRequest`
        """
        model = ActiveLearningIterationRequest()
        if include_optional:
            return ActiveLearningIterationRequest(
                campaign_config = biocentral_api._generated.models.active_learning_campaign_config.ActiveLearningCampaignConfig(
                    name = '', 
                    model_type = 'GAUSSIAN_PROCESS', 
                    embedder_name = '', 
                    optimization_mode = 'INTERVAL', 
                    target_lb = 1.337, 
                    target_ub = 1.337, 
                    target_value = 1.337, 
                    discrete_targets = [
                        ''
                        ], ),
                iteration_config = biocentral_api._generated.models.active_learning_iteration_config.ActiveLearningIterationConfig(
                    iteration_data = [
                        biocentral_api._generated.models.sequence_training_data.SequenceTrainingData(
                            seq_id = '0', 
                            sequence = '0', 
                            label = '', 
                            set = '', 
                            mask = '', )
                        ], 
                    coefficient = 0.0, 
                    n_suggestions = 1.0, )
            )
        else:
            return ActiveLearningIterationRequest(
                campaign_config = biocentral_api._generated.models.active_learning_campaign_config.ActiveLearningCampaignConfig(
                    name = '', 
                    model_type = 'GAUSSIAN_PROCESS', 
                    embedder_name = '', 
                    optimization_mode = 'INTERVAL', 
                    target_lb = 1.337, 
                    target_ub = 1.337, 
                    target_value = 1.337, 
                    discrete_targets = [
                        ''
                        ], ),
                iteration_config = biocentral_api._generated.models.active_learning_iteration_config.ActiveLearningIterationConfig(
                    iteration_data = [
                        biocentral_api._generated.models.sequence_training_data.SequenceTrainingData(
                            seq_id = '0', 
                            sequence = '0', 
                            label = '', 
                            set = '', 
                            mask = '', )
                        ], 
                    coefficient = 0.0, 
                    n_suggestions = 1.0, ),
        )
        """

    def testActiveLearningIterationRequest(self):
        """Test ActiveLearningIterationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
