# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_server_api._generated.models.continuous_optimization_config import ContinuousOptimizationConfig

class TestContinuousOptimizationConfig(unittest.TestCase):
    """ContinuousOptimizationConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContinuousOptimizationConfig:
        """Test ContinuousOptimizationConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContinuousOptimizationConfig`
        """
        model = ContinuousOptimizationConfig()
        if include_optional:
            return ContinuousOptimizationConfig(
                discrete = false,
                optimization_mode = 'interval',
                target_lb = None,
                target_ub = None,
                target_value = None
            )
        else:
            return ContinuousOptimizationConfig(
                optimization_mode = 'interval',
        )
        """

    def testContinuousOptimizationConfig(self):
        """Test ContinuousOptimizationConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
