# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_api._generated.api.biocentral_service_api import BiocentralServiceApi


class TestBiocentralServiceApi(unittest.TestCase):
    """BiocentralServiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BiocentralServiceApi()

    def tearDown(self) -> None:
        pass

    def test_stats_api_v1_biocentral_service_stats_get(self) -> None:
        """Test case for stats_api_v1_biocentral_service_stats_get

        Stats
        """
        pass

    def test_task_status_api_v1_biocentral_service_task_status_task_id_get(self) -> None:
        """Test case for task_status_api_v1_biocentral_service_task_status_task_id_get

        Task Status
        """
        pass

    def test_task_status_resumed_api_v1_biocentral_service_task_status_resumed_task_id_get(self) -> None:
        """Test case for task_status_resumed_api_v1_biocentral_service_task_status_resumed_task_id_get

        Task Status Resumed
        """
        pass

    def test_welcome_message_api_v1_biocentral_service_welcome_message_get(self) -> None:
        """Test case for welcome_message_api_v1_biocentral_service_welcome_message_get

        Welcome Message
        """
        pass


if __name__ == '__main__':
    unittest.main()
