# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_api._generated.models.embedding_progress import EmbeddingProgress

class TestEmbeddingProgress(unittest.TestCase):
    """EmbeddingProgress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmbeddingProgress:
        """Test EmbeddingProgress
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmbeddingProgress`
        """
        model = EmbeddingProgress()
        if include_optional:
            return EmbeddingProgress(
                current = 56,
                total = 56
            )
        else:
            return EmbeddingProgress(
                current = 56,
                total = 56,
        )
        """

    def testEmbeddingProgress(self):
        """Test EmbeddingProgress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
