# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_server_api._generated.api.custom_models_api import CustomModelsApi


class TestCustomModelsApi(unittest.TestCase):
    """CustomModelsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CustomModelsApi()

    def tearDown(self) -> None:
        pass

    def test_config_options_api_v1_custom_models_service_config_options_protocol_get(self) -> None:
        """Test case for config_options_api_v1_custom_models_service_config_options_protocol_get

        Get configuration options for a protocol
        """
        pass

    def test_model_files_api_v1_custom_models_service_model_files_post(self) -> None:
        """Test case for model_files_api_v1_custom_models_service_model_files_post

        Retrieve model files
        """
        pass

    def test_protocols_api_v1_custom_models_service_protocols_get(self) -> None:
        """Test case for protocols_api_v1_custom_models_service_protocols_get

        Get available protocols
        """
        pass

    def test_start_inference_api_v1_custom_models_service_start_inference_post(self) -> None:
        """Test case for start_inference_api_v1_custom_models_service_start_inference_post

        Start model inference
        """
        pass

    def test_start_training_api_v1_custom_models_service_start_training_post(self) -> None:
        """Test case for start_training_api_v1_custom_models_service_start_training_post

        Start model training
        """
        pass

    def test_verify_config_api_v1_custom_models_service_verify_config_post(self) -> None:
        """Test case for verify_config_api_v1_custom_models_service_verify_config_post

        Verify configuration
        """
        pass


if __name__ == '__main__':
    unittest.main()
