# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_server_api._generated.models.taxonomy_item import TaxonomyItem

class TestTaxonomyItem(unittest.TestCase):
    """TaxonomyItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaxonomyItem:
        """Test TaxonomyItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaxonomyItem`
        """
        model = TaxonomyItem()
        if include_optional:
            return TaxonomyItem(
                taxonomy_id = 56,
                name = '',
                family = ''
            )
        else:
            return TaxonomyItem(
                taxonomy_id = 56,
                name = '',
                family = '',
        )
        """

    def testTaxonomyItem(self):
        """Test TaxonomyItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
