# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_server_api._generated.api.ppi_api import PpiApi


class TestPpiApi(unittest.TestCase):
    """PpiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PpiApi()

    def tearDown(self) -> None:
        pass

    def test_auto_detect_format_by_header_api_v1_ppi_service_auto_detect_format_post(self) -> None:
        """Test case for auto_detect_format_by_header_api_v1_ppi_service_auto_detect_format_post

        Auto Detect Format By Header
        """
        pass

    def test_formats_api_v1_ppi_service_formats_get(self) -> None:
        """Test case for formats_api_v1_ppi_service_formats_get

        Formats
        """
        pass

    def test_import_dataset_api_v1_ppi_service_import_post(self) -> None:
        """Test case for import_dataset_api_v1_ppi_service_import_post

        Import Dataset
        """
        pass

    def test_run_test_api_v1_ppi_service_dataset_tests_run_test_post(self) -> None:
        """Test case for run_test_api_v1_ppi_service_dataset_tests_run_test_post

        Run Test
        """
        pass

    def test_tests_api_v1_ppi_service_dataset_tests_tests_get(self) -> None:
        """Test case for tests_api_v1_ppi_service_dataset_tests_tests_get

        Tests
        """
        pass


if __name__ == '__main__':
    unittest.main()
