# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_api._generated.models.model_metadata import ModelMetadata

class TestModelMetadata(unittest.TestCase):
    """ModelMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelMetadata:
        """Test ModelMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelMetadata`
        """
        model = ModelMetadata()
        if include_optional:
            return ModelMetadata(
                name = 'BindEmbed',
                protocol = '[0]',
                description = '',
                authors = '',
                model_link = '',
                citation = '',
                licence = '',
                outputs = [
                    biocentral_api._generated.models.model_output.ModelOutput(
                        name = '', 
                        description = '', 
                        output_type = 'per_residue', 
                        value_type = '', 
                        classes = [
                            biocentral_api._generated.models.output_class.OutputClass(
                                shortcut = '', 
                                label = '', 
                                description = '', )
                            ], 
                        value_range = [
                            null
                            ], 
                        unit = '', )
                    ],
                model_size = '',
                embedder = '',
                training_data_link = ''
            )
        else:
            return ModelMetadata(
                name = 'BindEmbed',
                protocol = '[0]',
                description = '',
                authors = '',
                model_link = '',
                citation = '',
                licence = '',
                outputs = [
                    biocentral_api._generated.models.model_output.ModelOutput(
                        name = '', 
                        description = '', 
                        output_type = 'per_residue', 
                        value_type = '', 
                        classes = [
                            biocentral_api._generated.models.output_class.OutputClass(
                                shortcut = '', 
                                label = '', 
                                description = '', )
                            ], 
                        value_range = [
                            null
                            ], 
                        unit = '', )
                    ],
                model_size = '',
                embedder = '',
        )
        """

    def testModelMetadata(self):
        """Test ModelMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
