# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_server_api._generated.api.embeddings_api import EmbeddingsApi


class TestEmbeddingsApi(unittest.TestCase):
    """EmbeddingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmbeddingsApi()

    def tearDown(self) -> None:
        pass

    def test_add_embeddings_api_v1_embeddings_service_add_embeddings_post(self) -> None:
        """Test case for add_embeddings_api_v1_embeddings_service_add_embeddings_post

        Add embeddings
        """
        pass

    def test_embed_api_v1_embeddings_service_embed_post(self) -> None:
        """Test case for embed_api_v1_embeddings_service_embed_post

        Calculate embeddings
        """
        pass

    def test_get_missing_embeddings_api_v1_embeddings_service_get_missing_embeddings_post(self) -> None:
        """Test case for get_missing_embeddings_api_v1_embeddings_service_get_missing_embeddings_post

        Check missing embeddings
        """
        pass


if __name__ == '__main__':
    unittest.main()
