# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_server_api._generated.models.task_dto import TaskDTO

class TestTaskDTO(unittest.TestCase):
    """TaskDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskDTO:
        """Test TaskDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskDTO`
        """
        model = TaskDTO()
        if include_optional:
            return TaskDTO(
                status = 0,
                error = '',
                predictions = {
                    'key' : null
                    },
                biotrainer_update = biocentral_server_api._generated.models.output_data.OutputData(
                    config = {
                        'key' : null
                        }, 
                    derived_values = {
                        'key' : null
                        }, 
                    split_specific_values = {
                        'key' : null
                        }, 
                    training_iteration = [
                        null
                        ], 
                    test_results = {
                        'key' : null
                        }, 
                    predictions = {
                        'key' : null
                        }, ),
                biotrainer_result = {
                    'key' : null
                    },
                embedding_current = 56,
                embedding_total = 56,
                embedded_sequences = {
                    'key' : ''
                    },
                embeddings = [
                    biocentral_server_api._generated.models.biotrainer_sequence_record.BiotrainerSequenceRecord(
                        seq_id = '0', 
                        seq = '', 
                        attributes = {
                            'key' : null
                            }, 
                        embedding = null, )
                    ],
                embeddings_file = '',
                embedder_name = '',
                autoeval_progress = biocentral_server_api._generated.models.auto_eval_progress.AutoEvalProgress(
                    completed_tasks = 56, 
                    total_tasks = 56, 
                    current_framework_name = '', 
                    current_task_name = '', 
                    final_report = {
                        'key' : null
                        }, ),
                bay_opt_results = [
                    null
                    ]
            )
        else:
            return TaskDTO(
                status = 0,
        )
        """

    def testTaskDTO(self):
        """Test TaskDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
