# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_server_api._generated.models.transfer_file_request import TransferFileRequest

class TestTransferFileRequest(unittest.TestCase):
    """TransferFileRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransferFileRequest:
        """Test TransferFileRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransferFileRequest`
        """
        model = TransferFileRequest()
        if include_optional:
            return TransferFileRequest(
                hash = '',
                file_type = '',
                file = ''
            )
        else:
            return TransferFileRequest(
                hash = '',
                file_type = '',
                file = '',
        )
        """

    def testTransferFileRequest(self):
        """Test TransferFileRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
