# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_api._generated.models.output_type import OutputType

class TestOutputType(unittest.TestCase):
    """OutputType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOutputType(self):
        """Test OutputType"""
        # inst = OutputType()

if __name__ == '__main__':
    unittest.main()
