# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_server_api._generated.models.config_option import ConfigOption

class TestConfigOption(unittest.TestCase):
    """ConfigOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigOption:
        """Test ConfigOption
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigOption`
        """
        model = ConfigOption()
        if include_optional:
            return ConfigOption(
                key = '',
                value = None
            )
        else:
            return ConfigOption(
                key = '',
                value = None,
        )
        """

    def testConfigOption(self):
        """Test ConfigOption"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
