# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_server_api._generated.api.bayesian_optimization_api import BayesianOptimizationApi


class TestBayesianOptimizationApi(unittest.TestCase):
    """BayesianOptimizationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BayesianOptimizationApi()

    def tearDown(self) -> None:
        pass

    def test_train_and_inference_api_v1_bayesian_optimization_service_training_post(self) -> None:
        """Test case for train_and_inference_api_v1_bayesian_optimization_service_training_post

        Start Bayesian optimization training
        """
        pass


if __name__ == '__main__':
    unittest.main()
