# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_api._generated.api.active_learning_api import ActiveLearningApi


class TestActiveLearningApi(unittest.TestCase):
    """ActiveLearningApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ActiveLearningApi()

    def tearDown(self) -> None:
        pass

    def test_active_learning_iteration_api_v1_active_learning_service_iteration_post(self) -> None:
        """Test case for active_learning_iteration_api_v1_active_learning_service_iteration_post

        Run one active learning iteration
        """
        pass


if __name__ == '__main__':
    unittest.main()
