# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_server_api._generated.models.target_lb import TargetLb

class TestTargetLb(unittest.TestCase):
    """TargetLb unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TargetLb:
        """Test TargetLb
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TargetLb`
        """
        model = TargetLb()
        if include_optional:
            return TargetLb(
            )
        else:
            return TargetLb(
        )
        """

    def testTargetLb(self):
        """Test TargetLb"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
