# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_api._generated.models.active_learning_simulation_config import ActiveLearningSimulationConfig

class TestActiveLearningSimulationConfig(unittest.TestCase):
    """ActiveLearningSimulationConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActiveLearningSimulationConfig:
        """Test ActiveLearningSimulationConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActiveLearningSimulationConfig`
        """
        model = ActiveLearningSimulationConfig()
        if include_optional:
            return ActiveLearningSimulationConfig(
                simulation_data = [
                    biocentral_api._generated.models.sequence_training_data.SequenceTrainingData(
                        seq_id = '0', 
                        sequence = '0', 
                        label = '', 
                        set = '', 
                        mask = '', )
                    ],
                n_start = 1.0,
                start_ids = [
                    ''
                    ],
                n_suggestions_per_iteration = 1.0,
                convergence_criterion = 0.0,
                n_max_iterations = 1.0
            )
        else:
            return ActiveLearningSimulationConfig(
                simulation_data = [
                    biocentral_api._generated.models.sequence_training_data.SequenceTrainingData(
                        seq_id = '0', 
                        sequence = '0', 
                        label = '', 
                        set = '', 
                        mask = '', )
                    ],
                n_suggestions_per_iteration = 1.0,
                convergence_criterion = 0.0,
                n_max_iterations = 1.0,
        )
        """

    def testActiveLearningSimulationConfig(self):
        """Test ActiveLearningSimulationConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
