# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_server_api._generated.models.start_task_response import StartTaskResponse

class TestStartTaskResponse(unittest.TestCase):
    """StartTaskResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StartTaskResponse:
        """Test StartTaskResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StartTaskResponse`
        """
        model = StartTaskResponse()
        if include_optional:
            return StartTaskResponse(
                task_id = ''
            )
        else:
            return StartTaskResponse(
                task_id = '',
        )
        """

    def testStartTaskResponse(self):
        """Test StartTaskResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
