# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_api._generated.api.projections_api import ProjectionsApi


class TestProjectionsApi(unittest.TestCase):
    """ProjectionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectionsApi()

    def tearDown(self) -> None:
        pass

    def test_project_api_v1_projection_service_project_post(self) -> None:
        """Test case for project_api_v1_projection_service_project_post

        Calculate projections
        """
        pass

    def test_projection_config_api_v1_projection_service_projection_config_get(self) -> None:
        """Test case for projection_config_api_v1_projection_service_projection_config_get

        Get Protspace config options
        """
        pass


if __name__ == '__main__':
    unittest.main()
