# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_server_api._generated.models.task_status_response import TaskStatusResponse

class TestTaskStatusResponse(unittest.TestCase):
    """TaskStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskStatusResponse:
        """Test TaskStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskStatusResponse`
        """
        model = TaskStatusResponse()
        if include_optional:
            return TaskStatusResponse(
                dtos = {
                    'key' : null
                    }
            )
        else:
            return TaskStatusResponse(
                dtos = {
                    'key' : null
                    },
        )
        """

    def testTaskStatusResponse(self):
        """Test TaskStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
