# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_server_api._generated.models.discrete_optimization_config import DiscreteOptimizationConfig

class TestDiscreteOptimizationConfig(unittest.TestCase):
    """DiscreteOptimizationConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DiscreteOptimizationConfig:
        """Test DiscreteOptimizationConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DiscreteOptimizationConfig`
        """
        model = DiscreteOptimizationConfig()
        if include_optional:
            return DiscreteOptimizationConfig(
                discrete = true,
                discrete_labels = None,
                discrete_targets = None
            )
        else:
            return DiscreteOptimizationConfig(
                discrete_labels = None,
                discrete_targets = None,
        )
        """

    def testDiscreteOptimizationConfig(self):
        """Test DiscreteOptimizationConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
