# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_api._generated.models.active_learning_model_type import ActiveLearningModelType

class TestActiveLearningModelType(unittest.TestCase):
    """ActiveLearningModelType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActiveLearningModelType(self):
        """Test ActiveLearningModelType"""
        # inst = ActiveLearningModelType()

if __name__ == '__main__':
    unittest.main()
