# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biocentral_api._generated.models.active_learning_iteration_config import ActiveLearningIterationConfig

class TestActiveLearningIterationConfig(unittest.TestCase):
    """ActiveLearningIterationConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActiveLearningIterationConfig:
        """Test ActiveLearningIterationConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActiveLearningIterationConfig`
        """
        model = ActiveLearningIterationConfig()
        if include_optional:
            return ActiveLearningIterationConfig(
                iteration_data = [
                    biocentral_api._generated.models.sequence_training_data.SequenceTrainingData(
                        seq_id = '0', 
                        sequence = '0', 
                        label = '', 
                        set = '', 
                        mask = '', )
                    ],
                coefficient = 0.0,
                n_suggestions = 1.0
            )
        else:
            return ActiveLearningIterationConfig(
                iteration_data = [
                    biocentral_api._generated.models.sequence_training_data.SequenceTrainingData(
                        seq_id = '0', 
                        sequence = '0', 
                        label = '', 
                        set = '', 
                        mask = '', )
                    ],
                coefficient = 0.0,
                n_suggestions = 1.0,
        )
        """

    def testActiveLearningIterationConfig(self):
        """Test ActiveLearningIterationConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
