include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

# Configure line length to 120
formatter:
  page_width: 120
