# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ActiveLearningConvergenceConfig(BaseModel):
    """
    Configuration for convergence criteria for active learning campaigns
    """ # noqa: E501
    max_labels_budget: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Maximum number of labels that can be tested in the lab ('We can afford to test 100 proteins total')")
    target_successes: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of positive targets found before stopping ('Stop when we find 10 good proteins')")
    max_consecutive_failures: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Maximum number of iterations in a row that do not yield a new target ('Stop if 3 rounds yield nothing')")
    __properties: ClassVar[List[str]] = ["max_labels_budget", "target_successes", "max_consecutive_failures"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ActiveLearningConvergenceConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if max_labels_budget (nullable) is None
        # and model_fields_set contains the field
        if self.max_labels_budget is None and "max_labels_budget" in self.model_fields_set:
            _dict['max_labels_budget'] = None

        # set to None if target_successes (nullable) is None
        # and model_fields_set contains the field
        if self.target_successes is None and "target_successes" in self.model_fields_set:
            _dict['target_successes'] = None

        # set to None if max_consecutive_failures (nullable) is None
        # and model_fields_set contains the field
        if self.max_consecutive_failures is None and "max_consecutive_failures" in self.model_fields_set:
            _dict['max_consecutive_failures'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ActiveLearningConvergenceConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "max_labels_budget": obj.get("max_labels_budget"),
            "target_successes": obj.get("target_successes"),
            "max_consecutive_failures": obj.get("max_consecutive_failures")
        })
        return _obj


