# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from biocentral_api._generated.models.active_learning_stopping_config import ActiveLearningStoppingConfig
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python
from biotrainer_core.data_classes import SequenceData

class ActiveLearningScreeningSimulationConfig(BaseModel):
    """
    Configuration for a simulation of active learning on a complete dataset
    """ # noqa: E501
    simulation_data: Annotated[List[SequenceData], Field(min_length=3)] = Field(description="List of all sequence data for the simulation")
    n_start: Optional[Annotated[int, Field(strict=True, ge=2)]] = Field(default=None, description="Number of initial sequences to use for training (chosen randomly, seed from campaign config used)")
    start_ids: Optional[Annotated[List[StrictStr], Field(min_length=2)]] = Field(default=None, description="List of sequence IDs to start the simulated campaign")
    n_suggestions_per_iteration: Annotated[int, Field(strict=True, ge=1)] = Field(description="Number of suggestions to propose per iteration")
    coefficient: Optional[Union[Annotated[float, Field(le=1.0, strict=True, ge=0.0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = Field(default=0.5, description="Exploitation-Exploration coefficient value, applied to every iteration (must be between 0 and 1, 1 is maximum exploration)")
    stopping_config: ActiveLearningStoppingConfig = Field(description="Stopping criteria for the simulation")
    hit_percentile: Optional[Union[Annotated[float, Field(lt=50.0, strict=True, gt=0.0)], Annotated[int, Field(lt=50, strict=True, gt=0)]]] = Field(default=1.0, description="Percentile of all labels that counts as a hit (modes: MAXIMIZE, MINIMIZE). 1.0 means the top/bottom 1% of the labels.")
    hit_target_delta: Optional[Union[Annotated[float, Field(strict=True, gt=0.0)], Annotated[int, Field(strict=True, gt=0)]]] = Field(default=0.5, description="Absolute tolerance around the target value that counts as a hit (mode: VALUE)")
    __properties: ClassVar[List[str]] = ["simulation_data", "n_start", "start_ids", "n_suggestions_per_iteration", "coefficient", "stopping_config", "hit_percentile", "hit_target_delta"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ActiveLearningScreeningSimulationConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in simulation_data (list)
        _items = []
        if self.simulation_data:
            for _item_simulation_data in self.simulation_data:
                if _item_simulation_data:
                    _items.append(_item_simulation_data.to_dict())
            _dict['simulation_data'] = _items
        # override the default output from pydantic by calling `to_dict()` of stopping_config
        if self.stopping_config:
            _dict['stopping_config'] = self.stopping_config.to_dict()
        # set to None if n_start (nullable) is None
        # and model_fields_set contains the field
        if self.n_start is None and "n_start" in self.model_fields_set:
            _dict['n_start'] = None

        # set to None if start_ids (nullable) is None
        # and model_fields_set contains the field
        if self.start_ids is None and "start_ids" in self.model_fields_set:
            _dict['start_ids'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ActiveLearningScreeningSimulationConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "simulation_data": [SequenceData.from_dict(_item) for _item in obj["simulation_data"]] if obj.get("simulation_data") is not None else None,
            "n_start": obj.get("n_start"),
            "start_ids": obj.get("start_ids"),
            "n_suggestions_per_iteration": obj.get("n_suggestions_per_iteration"),
            "coefficient": obj.get("coefficient") if obj.get("coefficient") is not None else 0.5,
            "stopping_config": ActiveLearningStoppingConfig.from_dict(obj["stopping_config"]) if obj.get("stopping_config") is not None else None,
            "hit_percentile": obj.get("hit_percentile") if obj.get("hit_percentile") is not None else 1.0,
            "hit_target_delta": obj.get("hit_target_delta") if obj.get("hit_target_delta") is not None else 0.5
        })
        return _obj


