# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from biocentral_api._generated.models.active_learning_model_type import ActiveLearningModelType
from biocentral_api._generated.models.active_learning_optimization_mode import ActiveLearningOptimizationMode
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ActiveLearningEngineeringCampaignConfig(BaseModel):
    """
    Configuration for an active learning engineering campaign
    """ # noqa: E501
    embedder_name: StrictStr = Field(description="Name of the embedder model to use")
    name: StrictStr = Field(description="Name of the active learning campaign")
    model_type: ActiveLearningModelType = Field(description="Type of model to use")
    optimization_mode: ActiveLearningOptimizationMode = Field(description="Optimization mode selection")
    seed: Optional[StrictInt] = Field(default=None, description="Random seed for reproducibility.")
    wildtype_sequence: StrictStr = Field(description="Wildtype sequence to engineer")
    __properties: ClassVar[List[str]] = ["embedder_name", "name", "model_type", "optimization_mode", "seed", "wildtype_sequence"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ActiveLearningEngineeringCampaignConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if seed (nullable) is None
        # and model_fields_set contains the field
        if self.seed is None and "seed" in self.model_fields_set:
            _dict['seed'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ActiveLearningEngineeringCampaignConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "embedder_name": obj.get("embedder_name"),
            "name": obj.get("name"),
            "model_type": obj.get("model_type"),
            "optimization_mode": obj.get("optimization_mode"),
            "seed": obj.get("seed"),
            "wildtype_sequence": obj.get("wildtype_sequence")
        })
        return _obj


