# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from biocentral_api._generated.models.sequence_training_data import SequenceTrainingData
from typing import Optional, Set
from typing_extensions import Self

class ActiveLearningSimulationConfig(BaseModel):
    """
    Configuration for a simulation of active learning on a complete dataset
    """ # noqa: E501
    simulation_data: Annotated[List[SequenceTrainingData], Field(min_length=2)] = Field(description="List of all sequence data for the simulation")
    n_start: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    start_ids: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = None
    n_suggestions_per_iteration: Annotated[int, Field(strict=True, ge=1)] = Field(description="Number of suggestions to propose per iteration")
    convergence_criterion: Union[Annotated[float, Field(le=1.0, strict=True, ge=0.0)], Annotated[int, Field(le=1, strict=True, ge=0)]] = Field(description="Convergence criterion for the simulation. The simulation stops after two iterations that fulfill the criterion (>= convergence_criterion suggestions fulfill the optimization target)")
    n_max_iterations: Annotated[int, Field(strict=True, ge=1)] = Field(description="Maximum number of iterations to run the simulation")
    __properties: ClassVar[List[str]] = ["simulation_data", "n_start", "start_ids", "n_suggestions_per_iteration", "convergence_criterion", "n_max_iterations"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ActiveLearningSimulationConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in simulation_data (list)
        _items = []
        if self.simulation_data:
            for _item_simulation_data in self.simulation_data:
                if _item_simulation_data:
                    _items.append(_item_simulation_data.to_dict())
            _dict['simulation_data'] = _items
        # set to None if n_start (nullable) is None
        # and model_fields_set contains the field
        if self.n_start is None and "n_start" in self.model_fields_set:
            _dict['n_start'] = None

        # set to None if start_ids (nullable) is None
        # and model_fields_set contains the field
        if self.start_ids is None and "start_ids" in self.model_fields_set:
            _dict['start_ids'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ActiveLearningSimulationConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "simulation_data": [SequenceTrainingData.from_dict(_item) for _item in obj["simulation_data"]] if obj.get("simulation_data") is not None else None,
            "n_start": obj.get("n_start"),
            "start_ids": obj.get("start_ids"),
            "n_suggestions_per_iteration": obj.get("n_suggestions_per_iteration"),
            "convergence_criterion": obj.get("convergence_criterion"),
            "n_max_iterations": obj.get("n_max_iterations")
        })
        return _obj


