# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Union
from typing_extensions import Annotated
from biocentral_api._generated.models.sequence_training_data import SequenceTrainingData
from typing import Optional, Set
from typing_extensions import Self

class ActiveLearningIterationConfig(BaseModel):
    """
    Configuration for a single iteration of active learning
    """ # noqa: E501
    iteration_data: Annotated[List[SequenceTrainingData], Field(min_length=2)] = Field(description="List of sequence training data for this iteration")
    coefficient: Union[Annotated[float, Field(le=1.0, strict=True, ge=0.0)], Annotated[int, Field(le=1, strict=True, ge=0)]] = Field(description="Exploitation-Exploration Coefficient value (must be between 0 and 1, 1 is maximum exploration)")
    n_suggestions: Annotated[int, Field(strict=True, ge=1)] = Field(description="Number of suggestions to propose from this iteration")
    __properties: ClassVar[List[str]] = ["iteration_data", "coefficient", "n_suggestions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ActiveLearningIterationConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in iteration_data (list)
        _items = []
        if self.iteration_data:
            for _item_iteration_data in self.iteration_data:
                if _item_iteration_data:
                    _items.append(_item_iteration_data.to_dict())
            _dict['iteration_data'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ActiveLearningIterationConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "iteration_data": [SequenceTrainingData.from_dict(_item) for _item in obj["iteration_data"]] if obj.get("iteration_data") is not None else None,
            "coefficient": obj.get("coefficient"),
            "n_suggestions": obj.get("n_suggestions")
        })
        return _obj


