# coding: utf-8

"""
Biocentral Server

API for biocentral services

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from biocentral_api._generated.models.biotrainer_model_result import (
    BiotrainerModelResult,
)
from typing import Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


class BiotrainerModelUpdate(BaseModel):
    """
    BiotrainerModelUpdate
    """  # noqa: E501

    current_model_result: BiotrainerModelResult = Field(
        description="Current model result"
    )
    training_iteration: Optional[
        Annotated[List[Any], Field(min_length=2, max_length=2)]
    ] = Field(
        default=None,
        description="Current training iteration for fast updates of observers like tensorboard",
    )
    __properties: ClassVar[List[str]] = ["current_model_result", "training_iteration"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BiotrainerModelUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of current_model_result
        if self.current_model_result:
            _dict["current_model_result"] = self.current_model_result.to_dict()
        # set to None if training_iteration (nullable) is None
        # and model_fields_set contains the field
        if (
            self.training_iteration is None
            and "training_iteration" in self.model_fields_set
        ):
            _dict["training_iteration"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BiotrainerModelUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "current_model_result": BiotrainerModelResult.from_dict(
                    obj["current_model_result"]
                )
                if obj.get("current_model_result") is not None
                else None,
                "training_iteration": obj.get("training_iteration"),
            }
        )
        return _obj
