# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CommonEmbedder(str, Enum):
    """
    Common embedder model names
    """

    """
    allowed enum values
    """
    ProtT5 = 'Rostlab/prot_t5_xl_uniref50'
    ProstT5 = 'Rostlab/ProstT5'
    ESM2_3B = 'facebook/esm2_t36_3B_UR50D'
    ESM2_650M = 'facebook/esm2_t33_650M_UR50D'
    ESM_8M = 'facebook/esm2_t6_8M_UR50D'
    ONE_HOT_ENCODING = 'one_hot_encoding'
    RANDOM_EMBEDDER = 'random_embedder'
    AAOntology = 'AAOntology'
    BLOSUM62 = 'blosum62'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CommonEmbedder from a JSON string"""
        return cls(json.loads(json_str))


