# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from biocentral_api._generated.models.embedding_stats import EmbeddingStats
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


class DerivedValues(BaseModel):
    """
    Derived values calculated during the training process. 
    """  # noqa: E501
    biotrainer_version: Optional[StrictStr] = Field(default=None, description="Version of BioTrainer used for training")
    class_int2str: Optional[Dict[str, StrictStr]] = Field(default=None,
                                                          description="Mapping of class integers to class names")
    class_str2int: Optional[Dict[str, StrictInt]] = Field(default=None,
                                                          description="Mapping of class names to class integers")
    computed_class_weights: Optional[Dict[str, Union[StrictFloat, StrictInt]]] = Field(default=None,
                                                                                       description="Class weights computed during training")
    embedding_stats: Optional[EmbeddingStats] = Field(default=None, description="Statistics of the embeddings")
    embeddings_file: Optional[StrictStr] = Field(default=None, description="Path to the embeddings file")
    model_hash: Optional[StrictStr] = Field(default=None, description="Hash of the model")
    n_classes: Optional[StrictInt] = Field(default=None, description="Number of classes in the dataset")
    n_features: Optional[StrictInt] = Field(default=None,
                                            description="Number of input features (e.g. embedding dimensions)")
    n_testing_ids: Optional[StrictInt] = Field(default=None, description="Number of sequences in the test set")
    pipeline_elapsed_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None,
                                                                           description="Elapsed time in seconds for the pipeline")
    pipeline_end_time: Optional[StrictStr] = Field(default=None, description="End time of the pipeline")
    pipeline_start_time: Optional[StrictStr] = Field(default=None, description="Start time of the pipeline")
    training_elapsed_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None,
                                                                           description="Elapsed time in seconds for training")
    __properties: ClassVar[List[str]] = ["biotrainer_version", "class_int2str", "class_str2int",
                                         "computed_class_weights", "embedding_stats", "embeddings_file", "model_hash",
                                         "n_classes", "n_features", "n_testing_ids", "pipeline_elapsed_time",
                                         "pipeline_end_time", "pipeline_start_time", "training_elapsed_time"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DerivedValues from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of embedding_stats
        if self.embedding_stats:
            _dict['embedding_stats'] = self.embedding_stats.to_dict()
        # set to None if biotrainer_version (nullable) is None
        # and model_fields_set contains the field
        if self.biotrainer_version is None and "biotrainer_version" in self.model_fields_set:
            _dict['biotrainer_version'] = None

        # set to None if class_int2str (nullable) is None
        # and model_fields_set contains the field
        if self.class_int2str is None and "class_int2str" in self.model_fields_set:
            _dict['class_int2str'] = None

        # set to None if class_str2int (nullable) is None
        # and model_fields_set contains the field
        if self.class_str2int is None and "class_str2int" in self.model_fields_set:
            _dict['class_str2int'] = None

        # set to None if computed_class_weights (nullable) is None
        # and model_fields_set contains the field
        if self.computed_class_weights is None and "computed_class_weights" in self.model_fields_set:
            _dict['computed_class_weights'] = None

        # set to None if embedding_stats (nullable) is None
        # and model_fields_set contains the field
        if self.embedding_stats is None and "embedding_stats" in self.model_fields_set:
            _dict['embedding_stats'] = None

        # set to None if embeddings_file (nullable) is None
        # and model_fields_set contains the field
        if self.embeddings_file is None and "embeddings_file" in self.model_fields_set:
            _dict['embeddings_file'] = None

        # set to None if model_hash (nullable) is None
        # and model_fields_set contains the field
        if self.model_hash is None and "model_hash" in self.model_fields_set:
            _dict['model_hash'] = None

        # set to None if n_classes (nullable) is None
        # and model_fields_set contains the field
        if self.n_classes is None and "n_classes" in self.model_fields_set:
            _dict['n_classes'] = None

        # set to None if n_features (nullable) is None
        # and model_fields_set contains the field
        if self.n_features is None and "n_features" in self.model_fields_set:
            _dict['n_features'] = None

        # set to None if n_testing_ids (nullable) is None
        # and model_fields_set contains the field
        if self.n_testing_ids is None and "n_testing_ids" in self.model_fields_set:
            _dict['n_testing_ids'] = None

        # set to None if pipeline_elapsed_time (nullable) is None
        # and model_fields_set contains the field
        if self.pipeline_elapsed_time is None and "pipeline_elapsed_time" in self.model_fields_set:
            _dict['pipeline_elapsed_time'] = None

        # set to None if pipeline_end_time (nullable) is None
        # and model_fields_set contains the field
        if self.pipeline_end_time is None and "pipeline_end_time" in self.model_fields_set:
            _dict['pipeline_end_time'] = None

        # set to None if pipeline_start_time (nullable) is None
        # and model_fields_set contains the field
        if self.pipeline_start_time is None and "pipeline_start_time" in self.model_fields_set:
            _dict['pipeline_start_time'] = None

        # set to None if training_elapsed_time (nullable) is None
        # and model_fields_set contains the field
        if self.training_elapsed_time is None and "training_elapsed_time" in self.model_fields_set:
            _dict['training_elapsed_time'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DerivedValues from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "biotrainer_version": obj.get("biotrainer_version"),
            "class_int2str": obj.get("class_int2str"),
            "class_str2int": obj.get("class_str2int"),
            "computed_class_weights": obj.get("computed_class_weights"),
            "embedding_stats": EmbeddingStats.from_dict(obj["embedding_stats"]) if obj.get(
                "embedding_stats") is not None else None,
            "embeddings_file": obj.get("embeddings_file"),
            "model_hash": obj.get("model_hash"),
            "n_classes": obj.get("n_classes"),
            "n_features": obj.get("n_features"),
            "n_testing_ids": obj.get("n_testing_ids"),
            "pipeline_elapsed_time": obj.get("pipeline_elapsed_time"),
            "pipeline_end_time": obj.get("pipeline_end_time"),
            "pipeline_start_time": obj.get("pipeline_start_time"),
            "training_elapsed_time": obj.get("training_elapsed_time")
        })
        return _obj
