# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from biocentral_api._generated.models.biocentral_prediction_model import BiocentralPredictionModel
from biocentral_api._generated.models.model_output import ModelOutput
from biocentral_api._generated.models.protocol import Protocol
from typing import Optional, Set
from typing_extensions import Self

class ModelMetadata(BaseModel):
    """
    ModelMetadata
    """ # noqa: E501
    name: BiocentralPredictionModel = Field(description="Model name")
    protocol: Protocol = Field(description="Protocol of model predictions")
    description: StrictStr = Field(description="Model description")
    authors: StrictStr = Field(description="Authors of the model")
    model_link: StrictStr = Field(description="Link to the model's repository")
    citation: StrictStr = Field(description="Citation of the model")
    licence: StrictStr = Field(description="Licence of the model")
    outputs: List[ModelOutput] = Field(description="List of descriptions of model outputs")
    model_size: StrictStr = Field(description="Size of the model in MB")
    embedder: StrictStr = Field(description="Name of the embedder used for the model")
    training_data_link: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["name", "protocol", "description", "authors", "model_link", "citation", "licence", "outputs", "model_size", "embedder", "training_data_link"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModelMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in outputs (list)
        _items = []
        if self.outputs:
            for _item_outputs in self.outputs:
                if _item_outputs:
                    _items.append(_item_outputs.to_dict())
            _dict['outputs'] = _items
        # set to None if training_data_link (nullable) is None
        # and model_fields_set contains the field
        if self.training_data_link is None and "training_data_link" in self.model_fields_set:
            _dict['training_data_link'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModelMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "protocol": obj.get("protocol"),
            "description": obj.get("description"),
            "authors": obj.get("authors"),
            "model_link": obj.get("model_link"),
            "citation": obj.get("citation"),
            "licence": obj.get("licence"),
            "outputs": [ModelOutput.from_dict(_item) for _item in obj["outputs"]] if obj.get("outputs") is not None else None,
            "model_size": obj.get("model_size"),
            "embedder": obj.get("embedder"),
            "training_data_link": obj.get("training_data_link")
        })
        return _obj


