# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class OutputType(str, Enum):
    """
    OutputType
    """

    """
    allowed enum values
    """
    PER_RESIDUE = 'per_residue'
    PER_SEQUENCE = 'per_sequence'
    MUTATION = 'mutation'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OutputType from a JSON string"""
        return cls(json.loads(json_str))


