# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Protocol(str, Enum):
    """
    Protocol
    """

    """
    allowed enum values
    """
    LEFT_SQUARE_BRACKET_0_RIGHT_SQUARE_BRACKET = '[0]'
    LEFT_SQUARE_BRACKET_1_RIGHT_SQUARE_BRACKET = '[1]'
    LEFT_SQUARE_BRACKET_2_RIGHT_SQUARE_BRACKET = '[2]'
    LEFT_SQUARE_BRACKET_3_RIGHT_SQUARE_BRACKET = '[3]'
    LEFT_SQUARE_BRACKET_4_RIGHT_SQUARE_BRACKET = '[4]'
    ENUM_5 = '5'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Protocol from a JSON string"""
        return cls(json.loads(json_str))


