# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Protocol(str, Enum):
    """
    Protocol
    """

    """
    allowed enum values
    """
    RESIDUE_TO_VALUE = 'residue_to_value'
    RESIDUE_TO_CLASS = 'residue_to_class'
    RESIDUES_TO_CLASS = 'residues_to_class'
    RESIDUES_TO_VALUE = 'residues_to_value'
    SEQUENCE_TO_CLASS = 'sequence_to_class'
    SEQUENCE_TO_VALUE = 'sequence_to_value'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Protocol from a JSON string"""
        return cls(json.loads(json_str))


