# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

class ResearchStats(BaseModel):
    """
    ResearchStats
    """ # noqa: E501
    total_sequences_today: StrictInt = Field(description="Total number of sequences uploaded in the last 24 hours")
    total_sequences_all_time: StrictInt = Field(description="Total number of sequences uploaded in all time")
    avg_sequence_length: Union[StrictFloat, StrictInt] = Field(description="Average length of sequences uploaded")
    aa_distribution: Dict[str, StrictInt] = Field(description="Distribution of amino acids in the sequences")
    top_embedders: Dict[str, Union[StrictFloat, StrictInt]] = Field(description="Top embedders based on usage")
    top_predictors: Dict[str, Union[StrictFloat, StrictInt]] = Field(description="Top prediction models based on usage")
    updated_at: datetime = Field(description="Timestamp of the last update")
    __properties: ClassVar[List[str]] = ["total_sequences_today", "total_sequences_all_time", "avg_sequence_length", "aa_distribution", "top_embedders", "top_predictors", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResearchStats from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResearchStats from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "total_sequences_today": obj.get("total_sequences_today"),
            "total_sequences_all_time": obj.get("total_sequences_all_time"),
            "avg_sequence_length": obj.get("avg_sequence_length"),
            "aa_distribution": obj.get("aa_distribution"),
            "top_embedders": obj.get("top_embedders"),
            "top_predictors": obj.get("top_predictors"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


