# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from biocentral_api._generated.models.sequence_training_data import SequenceTrainingData
from typing import Optional, Set
from typing_extensions import Self

class StartTrainingRequest(BaseModel):
    """
    StartTrainingRequest
    """ # noqa: E501
    config_dict: Dict[str, Any] = Field(description="Biotrainer configuration")
    training_data: Annotated[List[SequenceTrainingData], Field(min_length=1)] = Field(description="List of sequence training data")
    __properties: ClassVar[List[str]] = ["config_dict", "training_data"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StartTrainingRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in training_data (list)
        _items = []
        if self.training_data:
            for _item_training_data in self.training_data:
                if _item_training_data:
                    _items.append(_item_training_data.to_dict())
            _dict['training_data'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StartTrainingRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "config_dict": obj.get("config_dict"),
            "training_data": [SequenceTrainingData.from_dict(_item) for _item in obj["training_data"]] if obj.get("training_data") is not None else None
        })
        return _obj


