# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from biocentral_api._generated.models.auto_eval_progress import AutoEvalProgress
from biocentral_api._generated.models.biotrainer_sequence_record import BiotrainerSequenceRecord
from biocentral_api._generated.models.output_data import OutputData
from biocentral_api._generated.models.prediction import Prediction
from biocentral_api._generated.models.task_status import TaskStatus
from typing import Optional, Set
from typing_extensions import Self

class TaskDTO(BaseModel):
    """
    TaskDTO
    """ # noqa: E501
    status: TaskStatus
    error: Optional[StrictStr] = None
    predictions: Optional[Dict[str, List[Prediction]]] = None
    biotrainer_update: Optional[OutputData] = None
    biotrainer_result: Optional[Dict[str, Any]] = None
    embedding_current: Optional[StrictInt] = None
    embedding_total: Optional[StrictInt] = None
    embedded_sequences: Optional[Dict[str, StrictStr]] = None
    embeddings: Optional[List[BiotrainerSequenceRecord]] = None
    embeddings_file: Optional[StrictStr] = None
    projection_result: Optional[Dict[str, Any]] = None
    embedder_name: Optional[StrictStr] = None
    autoeval_progress: Optional[AutoEvalProgress] = None
    bay_opt_results: Optional[List[Any]] = None
    __properties: ClassVar[List[str]] = ["status", "error", "predictions", "biotrainer_update", "biotrainer_result", "embedding_current", "embedding_total", "embedded_sequences", "embeddings", "embeddings_file", "projection_result", "embedder_name", "autoeval_progress", "bay_opt_results"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TaskDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in predictions (dict of array)
        _field_dict_of_array = {}
        if self.predictions:
            for _key_predictions in self.predictions:
                if self.predictions[_key_predictions] is not None:
                    _field_dict_of_array[_key_predictions] = [
                        _item.to_dict() for _item in self.predictions[_key_predictions]
                    ]
            _dict['predictions'] = _field_dict_of_array
        # override the default output from pydantic by calling `to_dict()` of biotrainer_update
        if self.biotrainer_update:
            _dict['biotrainer_update'] = self.biotrainer_update.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in embeddings (list)
        _items = []
        if self.embeddings:
            for _item_embeddings in self.embeddings:
                if _item_embeddings:
                    _items.append(_item_embeddings.to_dict())
            _dict['embeddings'] = _items
        # override the default output from pydantic by calling `to_dict()` of autoeval_progress
        if self.autoeval_progress:
            _dict['autoeval_progress'] = self.autoeval_progress.to_dict()
        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        # set to None if predictions (nullable) is None
        # and model_fields_set contains the field
        if self.predictions is None and "predictions" in self.model_fields_set:
            _dict['predictions'] = None

        # set to None if biotrainer_update (nullable) is None
        # and model_fields_set contains the field
        if self.biotrainer_update is None and "biotrainer_update" in self.model_fields_set:
            _dict['biotrainer_update'] = None

        # set to None if biotrainer_result (nullable) is None
        # and model_fields_set contains the field
        if self.biotrainer_result is None and "biotrainer_result" in self.model_fields_set:
            _dict['biotrainer_result'] = None

        # set to None if embedding_current (nullable) is None
        # and model_fields_set contains the field
        if self.embedding_current is None and "embedding_current" in self.model_fields_set:
            _dict['embedding_current'] = None

        # set to None if embedding_total (nullable) is None
        # and model_fields_set contains the field
        if self.embedding_total is None and "embedding_total" in self.model_fields_set:
            _dict['embedding_total'] = None

        # set to None if embedded_sequences (nullable) is None
        # and model_fields_set contains the field
        if self.embedded_sequences is None and "embedded_sequences" in self.model_fields_set:
            _dict['embedded_sequences'] = None

        # set to None if embeddings (nullable) is None
        # and model_fields_set contains the field
        if self.embeddings is None and "embeddings" in self.model_fields_set:
            _dict['embeddings'] = None

        # set to None if embeddings_file (nullable) is None
        # and model_fields_set contains the field
        if self.embeddings_file is None and "embeddings_file" in self.model_fields_set:
            _dict['embeddings_file'] = None

        # set to None if projection_result (nullable) is None
        # and model_fields_set contains the field
        if self.projection_result is None and "projection_result" in self.model_fields_set:
            _dict['projection_result'] = None

        # set to None if embedder_name (nullable) is None
        # and model_fields_set contains the field
        if self.embedder_name is None and "embedder_name" in self.model_fields_set:
            _dict['embedder_name'] = None

        # set to None if autoeval_progress (nullable) is None
        # and model_fields_set contains the field
        if self.autoeval_progress is None and "autoeval_progress" in self.model_fields_set:
            _dict['autoeval_progress'] = None

        # set to None if bay_opt_results (nullable) is None
        # and model_fields_set contains the field
        if self.bay_opt_results is None and "bay_opt_results" in self.model_fields_set:
            _dict['bay_opt_results'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TaskDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "error": obj.get("error"),
            "predictions": dict(
                (_k,
                        [Prediction.from_dict(_item) for _item in _v]
                        if _v is not None
                        else None
                )
                for _k, _v in obj.get("predictions", {}).items()
            ),
            "biotrainer_update": OutputData.from_dict(obj["biotrainer_update"]) if obj.get("biotrainer_update") is not None else None,
            "biotrainer_result": obj.get("biotrainer_result"),
            "embedding_current": obj.get("embedding_current"),
            "embedding_total": obj.get("embedding_total"),
            "embedded_sequences": obj.get("embedded_sequences"),
            "embeddings": [BiotrainerSequenceRecord.from_dict(_item) for _item in obj["embeddings"]] if obj.get("embeddings") is not None else None,
            "embeddings_file": obj.get("embeddings_file"),
            "projection_result": obj.get("projection_result"),
            "embedder_name": obj.get("embedder_name"),
            "autoeval_progress": AutoEvalProgress.from_dict(obj["autoeval_progress"]) if obj.get("autoeval_progress") is not None else None,
            "bay_opt_results": obj.get("bay_opt_results")
        })
        return _obj


