# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from biocentral_api._generated.models.active_learning_iteration_result import ActiveLearningIterationResult
from biocentral_api._generated.models.active_learning_screening_simulation_result import \
    ActiveLearningScreeningSimulationResult
from biocentral_api._generated.models.biotrainer_inference_result import BiotrainerInferenceResult
from biocentral_api._generated.models.biotrainer_model_result import BiotrainerModelResult
from biocentral_api._generated.models.biotrainer_model_update import BiotrainerModelUpdate
from biocentral_api._generated.models.embedding_progress import EmbeddingProgress
from biocentral_api._generated.models.prediction import Prediction
from biocentral_api._generated.models.projection_result import ProjectionResult
from biocentral_api._generated.models.task_status import TaskStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python
from biotrainer_core.data_classes import SequenceData


class TaskDTO(BaseModel):
    """
    TaskDTO
    """  # noqa: E501
    status: TaskStatus
    error: Optional[StrictStr] = None
    predictions: Optional[Dict[str, List[Prediction]]] = None
    biotrainer_update: Optional[BiotrainerModelUpdate] = None
    biotrainer_result: Optional[BiotrainerModelResult] = None
    biotrainer_inference_result: Optional[BiotrainerInferenceResult] = None
    embedding_progress: Optional[EmbeddingProgress] = None
    embedded_sequences: Optional[Dict[str, StrictStr]] = None
    embeddings: Optional[List[SequenceData]] = None
    embeddings_file: Optional[StrictStr] = None
    clustered_data: Optional[Dict[str, List[StrictStr]]] = None
    projection_result: Optional[ProjectionResult] = None
    al_iteration_result: Optional[ActiveLearningIterationResult] = None
    al_simulation_result: Optional[ActiveLearningScreeningSimulationResult] = None
    __properties: ClassVar[List[str]] = ["status", "error", "predictions", "biotrainer_update", "biotrainer_result",
                                         "biotrainer_inference_result", "embedding_progress", "embedded_sequences",
                                         "embeddings", "embeddings_file", "clustered_data", "projection_result",
                                         "al_iteration_result", "al_simulation_result"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TaskDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in predictions (dict of array)
        _field_dict_of_array = {}
        if self.predictions:
            for _key_predictions in self.predictions:
                if self.predictions[_key_predictions] is not None:
                    _field_dict_of_array[_key_predictions] = [
                        _item.to_dict() for _item in self.predictions[_key_predictions]
                    ]
            _dict['predictions'] = _field_dict_of_array
        # override the default output from pydantic by calling `to_dict()` of biotrainer_update
        if self.biotrainer_update:
            _dict['biotrainer_update'] = self.biotrainer_update.to_dict()
        # override the default output from pydantic by calling `to_dict()` of biotrainer_result
        if self.biotrainer_result:
            _dict['biotrainer_result'] = self.biotrainer_result.to_dict()
        # override the default output from pydantic by calling `to_dict()` of biotrainer_inference_result
        if self.biotrainer_inference_result:
            _dict['biotrainer_inference_result'] = self.biotrainer_inference_result.to_dict()
        # override the default output from pydantic by calling `to_dict()` of embedding_progress
        if self.embedding_progress:
            _dict['embedding_progress'] = self.embedding_progress.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in embeddings (list)
        _items = []
        if self.embeddings:
            for _item_embeddings in self.embeddings:
                if _item_embeddings:
                    _items.append(_item_embeddings.to_dict())
            _dict['embeddings'] = _items
        # override the default output from pydantic by calling `to_dict()` of projection_result
        if self.projection_result:
            _dict['projection_result'] = self.projection_result.to_dict()
        # override the default output from pydantic by calling `to_dict()` of al_iteration_result
        if self.al_iteration_result:
            _dict['al_iteration_result'] = self.al_iteration_result.to_dict()
        # override the default output from pydantic by calling `to_dict()` of al_simulation_result
        if self.al_simulation_result:
            _dict['al_simulation_result'] = self.al_simulation_result.to_dict()
        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        # set to None if predictions (nullable) is None
        # and model_fields_set contains the field
        if self.predictions is None and "predictions" in self.model_fields_set:
            _dict['predictions'] = None

        # set to None if biotrainer_update (nullable) is None
        # and model_fields_set contains the field
        if self.biotrainer_update is None and "biotrainer_update" in self.model_fields_set:
            _dict['biotrainer_update'] = None

        # set to None if biotrainer_result (nullable) is None
        # and model_fields_set contains the field
        if self.biotrainer_result is None and "biotrainer_result" in self.model_fields_set:
            _dict['biotrainer_result'] = None

        # set to None if biotrainer_inference_result (nullable) is None
        # and model_fields_set contains the field
        if self.biotrainer_inference_result is None and "biotrainer_inference_result" in self.model_fields_set:
            _dict['biotrainer_inference_result'] = None

        # set to None if embedding_progress (nullable) is None
        # and model_fields_set contains the field
        if self.embedding_progress is None and "embedding_progress" in self.model_fields_set:
            _dict['embedding_progress'] = None

        # set to None if embedded_sequences (nullable) is None
        # and model_fields_set contains the field
        if self.embedded_sequences is None and "embedded_sequences" in self.model_fields_set:
            _dict['embedded_sequences'] = None

        # set to None if embeddings (nullable) is None
        # and model_fields_set contains the field
        if self.embeddings is None and "embeddings" in self.model_fields_set:
            _dict['embeddings'] = None

        # set to None if embeddings_file (nullable) is None
        # and model_fields_set contains the field
        if self.embeddings_file is None and "embeddings_file" in self.model_fields_set:
            _dict['embeddings_file'] = None

        # set to None if clustered_data (nullable) is None
        # and model_fields_set contains the field
        if self.clustered_data is None and "clustered_data" in self.model_fields_set:
            _dict['clustered_data'] = None

        # set to None if projection_result (nullable) is None
        # and model_fields_set contains the field
        if self.projection_result is None and "projection_result" in self.model_fields_set:
            _dict['projection_result'] = None

        # set to None if al_iteration_result (nullable) is None
        # and model_fields_set contains the field
        if self.al_iteration_result is None and "al_iteration_result" in self.model_fields_set:
            _dict['al_iteration_result'] = None

        # set to None if al_simulation_result (nullable) is None
        # and model_fields_set contains the field
        if self.al_simulation_result is None and "al_simulation_result" in self.model_fields_set:
            _dict['al_simulation_result'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TaskDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "error": obj.get("error"),
            "predictions": {
                _k: [Prediction.from_dict(_item) for _item in _v] if _v is not None else None
                for _k, _v in obj["predictions"].items()
            }
            if obj.get("predictions") is not None
            else None,
            "biotrainer_update": BiotrainerModelUpdate.from_dict(obj["biotrainer_update"]) if obj.get(
                "biotrainer_update") is not None else None,
            "biotrainer_result": BiotrainerModelResult.from_dict(obj["biotrainer_result"]) if obj.get(
                "biotrainer_result") is not None else None,
            "biotrainer_inference_result": BiotrainerInferenceResult.from_dict(
                obj["biotrainer_inference_result"]) if obj.get("biotrainer_inference_result") is not None else None,
            "embedding_progress": EmbeddingProgress.from_dict(obj["embedding_progress"]) if obj.get(
                "embedding_progress") is not None else None,
            "embedded_sequences": obj.get("embedded_sequences"),
            "embeddings": [SequenceData.from_dict(_item) for _item in obj["embeddings"]] if obj.get(
                "embeddings") is not None else None,
            "embeddings_file": obj.get("embeddings_file"),
            "clustered_data": obj.get("clustered_data"),
            "projection_result": ProjectionResult.from_dict(obj["projection_result"]) if obj.get(
                "projection_result") is not None else None,
            "al_iteration_result": ActiveLearningIterationResult.from_dict(obj["al_iteration_result"]) if obj.get(
                "al_iteration_result") is not None else None,
            "al_simulation_result": ActiveLearningScreeningSimulationResult.from_dict(
                obj["al_simulation_result"]) if obj.get("al_simulation_result") is not None else None
        })
        return _obj
