# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from biocentral_api._generated.models.ranking_result import RankingResult
from biocentral_api._generated.models.zero_shot_method import ZeroShotMethod
from typing import Optional, Set
from typing_extensions import Self

class ZeroShotFrameworkReport(BaseModel):
    """
    ZeroShotFrameworkReport
    """ # noqa: E501
    method: ZeroShotMethod = Field(description="Scoring method used")
    aggregated_results: Dict[str, RankingResult] = Field(description="Accumulated autoeval task results (combined_task_name -> RankingResult)")
    individual_results: Dict[str, RankingResult] = Field(description="Individual autoeval task results (dataset_name -> RankingResult)")
    __properties: ClassVar[List[str]] = ["method", "aggregated_results", "individual_results"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ZeroShotFrameworkReport from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in aggregated_results (dict)
        _field_dict = {}
        if self.aggregated_results:
            for _key_aggregated_results in self.aggregated_results:
                if self.aggregated_results[_key_aggregated_results]:
                    _field_dict[_key_aggregated_results] = self.aggregated_results[_key_aggregated_results].to_dict()
            _dict['aggregated_results'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in individual_results (dict)
        _field_dict = {}
        if self.individual_results:
            for _key_individual_results in self.individual_results:
                if self.individual_results[_key_individual_results]:
                    _field_dict[_key_individual_results] = self.individual_results[_key_individual_results].to_dict()
            _dict['individual_results'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ZeroShotFrameworkReport from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "method": obj.get("method"),
            "aggregated_results": dict(
                (_k, RankingResult.from_dict(_v))
                for _k, _v in obj["aggregated_results"].items()
            )
            if obj.get("aggregated_results") is not None
            else None,
            "individual_results": dict(
                (_k, RankingResult.from_dict(_v))
                for _k, _v in obj["individual_results"].items()
            )
            if obj.get("individual_results") is not None
            else None
        })
        return _obj


