# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ZeroShotMethod(str, Enum):
    """
    ZeroShotMethod
    """

    """
    allowed enum values
    """
    WT_MARGINALS = 'WT_MARGINALS'
    MASKED_MARGINALS = 'MASKED_MARGINALS'
    PSEUDOPERPLEXITY = 'PSEUDOPERPLEXITY'
    PERPLEXITY = 'PERPLEXITY'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ZeroShotMethod from a JSON string"""
        return cls(json.loads(json_str))


