name: "_internal_prott5_tokenizer"
backend: "python"
max_batch_size: 8

input [
  {
    name: "sequences"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

output [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [ -1 ]
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [ -1 ]
  }
] 