#!/usr/bin/env python3
"""
OpenAPI Client Generator Script

Generates basic clients from OpenAPI spec and moves generated docs to the appropriate directory.
Make sure you have the [openapi-generator-cli](https://openapi-generator.tech/docs/installation) installed.
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path


def run_command(command, cwd=None):
    """Run a shell command and handle errors."""
    print(f"Running: {' '.join(command)}")
    try:
        result = subprocess.run(
            command,
            cwd=cwd,
            check=True,
            capture_output=True,
            text=True
        )
        if result.stdout:
            print(result.stdout)
        if result.stderr:
            print(result.stderr)
        return True
    except subprocess.CalledProcessError as e:
        print(f"Error running command: {e}")
        if e.stderr:
            print(f"Error output: {e.stderr}")
        return False


def clean_directory(directory):
    """Clean a directory by removing all contents."""
    if directory.exists():
        print(f"Cleaning directory: {directory}")
        shutil.rmtree(directory)
    directory.mkdir(parents=True, exist_ok=True)


def move_generated_docs(source_docs_dir, target_docs_dir, existing_manual_docs):
    """Move generated documentation from source to target directory using rsync."""
    if not source_docs_dir.exists():
        print(f"Source docs directory not found: {source_docs_dir}")
        return False

    # Ensure target directory exists
    target_docs_dir.mkdir(parents=True, exist_ok=True)

    print(f"Syncing generated docs from {source_docs_dir} to {target_docs_dir}")

    try:
        # Use rsync to sync only the files that have changed
        # This preserves git's understanding of file modifications
        rsync_command = [
            "rsync",
            "-av",  # archive mode, verbose
            "--delete",  # delete files in target that don't exist in source
            "--exclude-from=-",  # exclude patterns from stdin
            f"{source_docs_dir}/",  # source (trailing slash important)
            f"{target_docs_dir}/"  # target
        ]

        # Create exclude patterns for manual docs
        exclude_patterns = "\n".join(existing_manual_docs) if existing_manual_docs else ""

        result = subprocess.run(
            rsync_command,
            input=exclude_patterns,
            text=True,
            check=True,
            capture_output=True
        )

        if result.stdout:
            print(result.stdout)

        # Remove generated files
        for file in source_docs_dir.iterdir():
            if file.is_file() and file.name not in existing_manual_docs:
                file.unlink()

        return True
    except subprocess.CalledProcessError as e:
        print(f"Error running rsync: {e}")
        if e.stderr:
            print(f"Error output: {e.stderr}")
        return False
    except Exception as e:
        print(f"Error syncing docs: {e}")
        return False


def read_generated_files_list(files_list_path: Path):
    """Read the list of files generated by OpenAPI generator from .openapi-generator/FILES.
    Returns a set of relative POSIX-style paths (relative to the language root folder).
    """
    generated = set()
    try:
        with files_list_path.open("r", encoding="utf-8") as f:
            for line in f:
                p = line.strip()
                if not p or p.startswith("#"):
                    continue
                # Normalize to POSIX-style relative paths
                generated.add(Path(p).as_posix())
    except FileNotFoundError:
        print(f"Warning: Generated files list not found: {files_list_path}")
    return generated


def prune_outdated_generated_code(lang_root: Path, generated_files: set):
    """Delete files under biocentral_api/_generated that are no longer generated.

    - lang_root: path to the python folder (e.g., repo/python)
    - generated_files: set of relative paths (as in .openapi-generator/FILES) rooted at lang_root
    """
    target_rel_prefix = "biocentral_api/_generated/"
    target_dir = lang_root / "biocentral_api" / "_generated"

    if not target_dir.exists():
        return

    # Build the allow-list for files under _generated
    allow = {p for p in generated_files if p.startswith(target_rel_prefix)}

    # Walk existing files and delete those not in allow list
    for root, _, files in os.walk(target_dir, topdown=False):
        for fname in files:
            full_path = Path(root) / fname
            rel_from_lang = full_path.relative_to(lang_root).as_posix()
            if rel_from_lang not in allow:
                print(f"Removing outdated generated file: {rel_from_lang}")
                try:
                    full_path.unlink()
                except Exception as e:
                    print(f"Failed to remove {full_path}: {e}")
        # Remove empty directories
        try:
            if not os.listdir(root):
                Path(root).rmdir()
        except OSError:
            # Directory not empty or other issue; ignore
            pass


def prune_outdated_generated_code_dart(lang_root: Path, generated_files: set):
    """Delete generated Dart files under lib/ that are no longer generated.

    - lang_root: path to the dart folder (e.g., repo/dart)
    - generated_files: set of relative paths (as in .openapi-generator/FILES) rooted at lang_root

    Safety: Only prune within directories that contain generated files (as reported in FILES),
    so manual Dart sources in other lib/ subfolders (e.g., lib/src/clients) are not touched.
    """
    excluded_dirs = ["clients", "tasks"]
    excluded_files = ["high_level_api.dart"]
    target_rel_prefix = "lib/"
    lib_dir = lang_root / "lib"

    if not lib_dir.exists():
        return

    # Build the allow-list for files under lib/
    allow = {p for p in generated_files if p.startswith(target_rel_prefix)}

    # Build set of directories that contain generated files; limit pruning to these
    prune_dirs = set()
    for p in allow:
        d = (lang_root / p).parent
        # Ensure the directory is within lib/
        try:
            d.relative_to(lib_dir)
            prune_dirs.add(d)
        except ValueError:
            # Outside lib/, ignore
            continue

    # Also include lib root if there are generated files directly under lib/
    has_lib_root_files = any(Path(p).parent.as_posix() == 'lib' for p in allow)
    if has_lib_root_files:
        prune_dirs.add(lib_dir)

    # Normalize allow to absolute Path objects for faster membership checks
    allow_abs = {(lang_root / p).as_posix() for p in allow}

    # Walk each prune_dir subtree and delete files not present in allow list
    for dir_root in sorted(prune_dirs):
        for root, _, files in os.walk(dir_root, topdown=False):
            if root.split("/")[-1] in excluded_dirs:
                continue
            for fname in files:
                if fname in excluded_files:
                    continue
                full_path = Path(root) / fname
                if full_path.as_posix() not in allow_abs:
                    rel_from_lang = full_path.relative_to(lang_root).as_posix()
                    print(f"Removing outdated generated Dart file: {rel_from_lang}")
                    try:
                        full_path.unlink()
                    except Exception as e:
                        print(f"Failed to remove {full_path}: {e}")


def git_add_generated_files(lang_root: Path, language: str):
    """Run git add on generated code and documentation directories.

    Args:
        lang_root: Path to the language root directory (e.g., repo/python or repo/dart)
        language: Either 'python' or 'dart' to determine which directories to add
    """
    if language == 'python':
        dirs_to_add = ['biocentral_api', 'docs']
    elif language == 'dart':
        dirs_to_add = ['lib', 'doc']
    else:
        print(f"Unknown language: {language}")
        return False

    success = True
    for dir_name in dirs_to_add:
        dir_path = lang_root / dir_name
        if dir_path.exists():
            git_command = ["git", "add", str(dir_path)]
            if run_command(git_command, cwd=lang_root):
                print(f"Successfully staged {dir_path}")
            else:
                print(f"Failed to stage {dir_path}")
                success = False
        else:
            print(f"Directory not found: {dir_path}")
            success = False

    return success


def generate_python():
    # Define paths
    script_dir = Path(__file__).parent
    openapi_spec = script_dir / "openapi.json"
    output_dir = script_dir.parent / "python"
    temp_docs_dir = output_dir / "docs"
    target_docs_dir = output_dir / "docs" / "_generated"

    # Check if OpenAPI spec exists
    if not openapi_spec.exists():
        print(f"Error: OpenAPI spec not found at {openapi_spec}")
        sys.exit(1)

    if not target_docs_dir.exists():
        target_docs_dir.mkdir(parents=True, exist_ok=True)

    existing_manual_docs = list(os.listdir(temp_docs_dir))

    # Prepare the openapi-generator command
    generator_command = [
        "openapi-generator-cli",
        "generate",
        "-g", "python",
        "--package-name", "biocentral_api._generated",
        "-i", str(openapi_spec),
        "-o", str(output_dir)
    ]

    print("Generating OpenAPI Python client...")

    # Run the generator
    if not run_command(generator_command, cwd=script_dir):
        print("Failed to generate OpenAPI client")
        sys.exit(1)

    print("OpenAPI client generated successfully!")

    # Check if docs were generated and need to be moved
    if temp_docs_dir.exists() and any(temp_docs_dir.iterdir()):
        print("Moving generated documentation...")

        # Ensure target directory exists
        target_docs_dir.parent.mkdir(parents=True, exist_ok=True)

        # Move generated docs
        if move_generated_docs(temp_docs_dir, target_docs_dir, existing_manual_docs):
            print("Documentation moved successfully!")
        else:
            print("Warning: Failed to move documentation")
            sys.exit(1)
    else:
        print("No generated documentation found to move")

    # After generation and doc move, prune outdated files and docs based on the current FILES list
    files_list_path = output_dir / ".openapi-generator" / "FILES"
    generated_files = read_generated_files_list(files_list_path)
    if generated_files:
        prune_outdated_generated_code(output_dir, generated_files)
    else:
        print("Warning: No generated files list found; skipping prune step.")

    git_add_generated_files(output_dir, "python")
    print("\nPython Generation complete!")
    print(f"Generated client is in: {output_dir}")
    print(f"Generated docs are in: {target_docs_dir}")


def generate_dart():
    # Define paths
    script_dir = Path(__file__).parent
    openapi_spec = script_dir / "openapi.json"
    output_dir = script_dir.parent / "dart"
    temp_docs_dir = output_dir / "doc"
    target_docs_dir = output_dir / "doc" / "_generated"

    # Check if OpenAPI spec exists
    if not openapi_spec.exists():
        print(f"Error: OpenAPI spec not found at {openapi_spec}")
        sys.exit(1)

    if not target_docs_dir.exists():
        target_docs_dir.mkdir(parents=True, exist_ok=True)

    existing_manual_docs = list(os.listdir(temp_docs_dir))

    # Prepare the openapi-generator command
    generator_command = [
        "openapi-generator-cli",
        "generate",
        "-g", "dart-dio",
        "--package-name", "biocentral_api",
        "--additional-properties=pubName=biocentral_api",
        "-i", str(openapi_spec),
        "-o", str(output_dir)
    ]

    print("Generating OpenAPI Dart client...")

    # Run the generator
    if not run_command(generator_command, cwd=script_dir):
        print("Failed to generate OpenAPI client")
        sys.exit(1)

    print("OpenAPI Dart client generated successfully!")

    # Run the builder
    # TODO Does not work automatically yet, because BiotrainerSequenceRecord needs manual refactoring after creation
    builder_command = [
        "/usr/bin/flutter/bin/dart",
        "run",
        "build_runner",
        "build",
        "--delete-conflicting-outputs"
    ]

    # if not run_command(builder_command, cwd=output_dir):
    #     print("Failed to generate Dart builder")
    #     sys.exit(1)

    # Check if docs were generated and need to be moved
    if temp_docs_dir.exists() and any(temp_docs_dir.iterdir()):
        print("Moving generated documentation...")

        # Ensure target directory exists
        target_docs_dir.parent.mkdir(parents=True, exist_ok=True)

        # Move generated docs
        if move_generated_docs(temp_docs_dir, target_docs_dir, existing_manual_docs):
            print("Documentation moved successfully!")
        else:
            print("Warning: Failed to move documentation")
            sys.exit(1)
    else:
        print("No generated documentation found to move")

    # After generation and (optional) doc move, prune outdated Dart generated files based on the current FILES list
    files_list_path = output_dir / ".openapi-generator" / "FILES"
    generated_files = read_generated_files_list(files_list_path)
    if generated_files:
        prune_outdated_generated_code_dart(output_dir, generated_files)
    else:
        print("Warning: No generated files list found for Dart; skipping prune step.")

    git_add_generated_files(output_dir, "dart")
    print("\nDart Generation complete!")
    print(f"Generated client is in: {output_dir}")
    print(f"Generated docs are in: {target_docs_dir}")


def main():
    """Main function to generate OpenAPI client and organize documentation."""
    # generate_python()
    generate_dart()


if __name__ == "__main__":
    main()
