# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class BayesianOptimizationRequest(BaseModel):
    """
    Request model for Bayesian optimization training
    """ # noqa: E501
    database_hash: StrictStr = Field(description="Hash identifier for the training database")
    model_type: StrictStr = Field(description="Type of model to use")
    coefficient: Union[Annotated[float, Field(strict=True, ge=0.0)], Annotated[int, Field(strict=True, ge=0)]] = Field(description="Coefficient value (must be non-negative)")
    embedder_name: StrictStr = Field(description="Name of embedder to use")
    discrete: StrictBool = Field(description="Whether to perform discrete optimization or continuous optimization")
    optimization_mode: StrictStr = Field(description="Optimization mode selection")
    target_lb: Optional[Union[StrictFloat, StrictInt]] = None
    target_ub: Optional[Union[StrictFloat, StrictInt]] = None
    target_value: Optional[Union[StrictFloat, StrictInt]] = None
    discrete_labels: Optional[List[StrictStr]]
    discrete_targets: Optional[List[StrictStr]]
    __properties: ClassVar[List[str]] = ["database_hash", "model_type", "coefficient", "embedder_name", "discrete", "optimization_mode", "target_lb", "target_ub", "target_value", "discrete_labels", "discrete_targets"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BayesianOptimizationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if target_lb (nullable) is None
        # and model_fields_set contains the field
        if self.target_lb is None and "target_lb" in self.model_fields_set:
            _dict['target_lb'] = None

        # set to None if target_ub (nullable) is None
        # and model_fields_set contains the field
        if self.target_ub is None and "target_ub" in self.model_fields_set:
            _dict['target_ub'] = None

        # set to None if target_value (nullable) is None
        # and model_fields_set contains the field
        if self.target_value is None and "target_value" in self.model_fields_set:
            _dict['target_value'] = None

        # set to None if discrete_labels (nullable) is None
        # and model_fields_set contains the field
        if self.discrete_labels is None and "discrete_labels" in self.model_fields_set:
            _dict['discrete_labels'] = None

        # set to None if discrete_targets (nullable) is None
        # and model_fields_set contains the field
        if self.discrete_targets is None and "discrete_targets" in self.model_fields_set:
            _dict['discrete_targets'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BayesianOptimizationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "database_hash": obj.get("database_hash"),
            "model_type": obj.get("model_type"),
            "coefficient": obj.get("coefficient"),
            "embedder_name": obj.get("embedder_name"),
            "discrete": obj.get("discrete"),
            "optimization_mode": obj.get("optimization_mode"),
            "target_lb": obj.get("target_lb"),
            "target_ub": obj.get("target_ub"),
            "target_value": obj.get("target_value"),
            "discrete_labels": obj.get("discrete_labels"),
            "discrete_targets": obj.get("discrete_targets")
        })
        return _obj


