# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from biocentral_server_api._generated.models.discrete_labels import DiscreteLabels
from biocentral_server_api._generated.models.discrete_targets import DiscreteTargets
from typing import Optional, Set
from typing_extensions import Self

class DiscreteOptimizationConfig(BaseModel):
    """
    Configuration for discrete optimization
    """ # noqa: E501
    discrete: Optional[StrictBool] = True
    discrete_labels: DiscreteLabels
    discrete_targets: DiscreteTargets
    __properties: ClassVar[List[str]] = ["discrete", "discrete_labels", "discrete_targets"]

    @field_validator('discrete')
    def discrete_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['true']):
            raise ValueError("must be one of enum values ('true')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DiscreteOptimizationConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of discrete_labels
        if self.discrete_labels:
            _dict['discrete_labels'] = self.discrete_labels.to_dict()
        # override the default output from pydantic by calling `to_dict()` of discrete_targets
        if self.discrete_targets:
            _dict['discrete_targets'] = self.discrete_targets.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DiscreteOptimizationConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "discrete": obj.get("discrete") if obj.get("discrete") is not None else True,
            "discrete_labels": DiscreteLabels.from_dict(obj["discrete_labels"]) if obj.get("discrete_labels") is not None else None,
            "discrete_targets": DiscreteTargets.from_dict(obj["discrete_targets"]) if obj.get("discrete_targets") is not None else None
        })
        return _obj


