# coding: utf-8

"""
    Biocentral Server

    API for biocentral services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class OutputData(BaseModel):
    """
    OutputData
    """ # noqa: E501
    config: Optional[Dict[str, Any]] = None
    derived_values: Optional[Dict[str, Any]] = None
    split_specific_values: Optional[Dict[str, Any]] = None
    training_iteration: Optional[Annotated[List[Any], Field(min_length=2, max_length=2)]] = None
    test_results: Optional[Dict[str, Any]] = None
    predictions: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["config", "derived_values", "split_specific_values", "training_iteration", "test_results", "predictions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OutputData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if config (nullable) is None
        # and model_fields_set contains the field
        if self.config is None and "config" in self.model_fields_set:
            _dict['config'] = None

        # set to None if derived_values (nullable) is None
        # and model_fields_set contains the field
        if self.derived_values is None and "derived_values" in self.model_fields_set:
            _dict['derived_values'] = None

        # set to None if split_specific_values (nullable) is None
        # and model_fields_set contains the field
        if self.split_specific_values is None and "split_specific_values" in self.model_fields_set:
            _dict['split_specific_values'] = None

        # set to None if training_iteration (nullable) is None
        # and model_fields_set contains the field
        if self.training_iteration is None and "training_iteration" in self.model_fields_set:
            _dict['training_iteration'] = None

        # set to None if test_results (nullable) is None
        # and model_fields_set contains the field
        if self.test_results is None and "test_results" in self.model_fields_set:
            _dict['test_results'] = None

        # set to None if predictions (nullable) is None
        # and model_fields_set contains the field
        if self.predictions is None and "predictions" in self.model_fields_set:
            _dict['predictions'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OutputData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "config": obj.get("config"),
            "derived_values": obj.get("derived_values"),
            "split_specific_values": obj.get("split_specific_values"),
            "training_iteration": obj.get("training_iteration"),
            "test_results": obj.get("test_results"),
            "predictions": obj.get("predictions")
        })
        return _obj


