name: "bind_embed"
platform: "onnxruntime_onnx"
max_batch_size: 16
default_model_filename: "cv_0.onnx"

input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ -1, -1 ]  # Variable shape input
  }
]

output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ -1 ]  # Variable output shape
  }
]

dynamic_batching {
  preferred_batch_size: [ 4, 8, 16 ]
  max_queue_delay_microseconds: 5000
}

instance_group [
  {
    count: 1
    kind: KIND_AUTO
  }
]