name: "bind_embed"
platform: "onnxruntime_onnx"
max_batch_size: 16
default_model_filename: "cv_0.onnx"

input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ -1, -1 ]  # Batch dimension included (fixed to 1)
  }
]

output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 3, -1 ]  # Batch dimension included
  }
]

instance_group [
  {
    count: 1
    kind: KIND_AUTO
  }
]